sudo: required
services:
  - docker

before_install:
  - docker build -t my-image -f Dockerfile.dev .

script:
  - docker run -e CI=true my-image npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-517639811334"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
